package terceros;


/**
* terceros/terceroPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tercero.idl
* miércoles 26 de septiembre de 2018 09:13:15 PM COT
*/

public abstract class terceroPOA extends org.omg.PortableServer.Servant
 implements terceros.terceroOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertartercero", new java.lang.Integer (0));
    _methods.put ("actualizartercero", new java.lang.Integer (1));
    _methods.put ("eliminartercero", new java.lang.Integer (2));
    _methods.put ("consultartercero", new java.lang.Integer (3));
    _methods.put ("shoutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // terceros/tercero/insertartercero
       {
         String nombre = in.read_wstring ();
         String apellido = in.read_wstring ();
         String telefono = in.read_wstring ();
         boolean $result = false;
         $result = this.insertartercero (nombre, apellido, telefono);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // terceros/tercero/actualizartercero
       {
         int id = in.read_long ();
         String nombre = in.read_wstring ();
         String apellido = in.read_wstring ();
         String telefono = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizartercero (id, nombre, apellido, telefono);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // terceros/tercero/eliminartercero
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.eliminartercero (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // terceros/tercero/consultartercero
       {
         int id = in.read_long ();
         String $result = null;
         $result = this.consultartercero (id);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // terceros/tercero/shoutdown
       {
         this.shoutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:terceros/tercero:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public tercero _this() 
  {
    return terceroHelper.narrow(
    super._this_object());
  }

  public tercero _this(org.omg.CORBA.ORB orb) 
  {
    return terceroHelper.narrow(
    super._this_object(orb));
  }


} // class terceroPOA
