package terceros;


/**
* terceros/terceroOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tercero.idl
* miércoles 26 de septiembre de 2018 09:13:15 PM COT
*/

public interface terceroOperations 
{
  boolean insertartercero (String nombre, String apellido, String telefono);
  boolean actualizartercero (int id, String nombre, String apellido, String telefono);
  boolean eliminartercero (int id);
  String consultartercero (int id);
  void shoutdown ();
} // interface terceroOperations
