package terceros;


/**
* terceros/terceroHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tercero.idl
* miércoles 26 de septiembre de 2018 09:13:15 PM COT
*/

abstract public class terceroHelper
{
  private static String  _id = "IDL:terceros/tercero:1.0";

  public static void insert (org.omg.CORBA.Any a, terceros.tercero that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static terceros.tercero extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (terceros.terceroHelper.id (), "tercero");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static terceros.tercero read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_terceroStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, terceros.tercero value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static terceros.tercero narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof terceros.tercero)
      return (terceros.tercero)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      terceros._terceroStub stub = new terceros._terceroStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static terceros.tercero unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof terceros.tercero)
      return (terceros.tercero)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      terceros._terceroStub stub = new terceros._terceroStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
