package terceros;


/**
* terceros/tercero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tercero.idl
* miércoles 26 de septiembre de 2018 09:13:15 PM COT
*/

public interface tercero extends terceroOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface tercero
