package terceros;

/**
* terceros/terceroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tercero.idl
* miércoles 26 de septiembre de 2018 09:13:15 PM COT
*/

public final class terceroHolder implements org.omg.CORBA.portable.Streamable
{
  public terceros.tercero value = null;

  public terceroHolder ()
  {
  }

  public terceroHolder (terceros.tercero initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = terceros.terceroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    terceros.terceroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return terceros.terceroHelper.type ();
  }

}
